# Generated by Django 4.1.2 on 2022-12-05 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_profiles_alter_jobs_id_alter_users_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='supabase_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
